### ISSUE TITLE
Create Session Packet Type test failing 

### ISSUE THREAD

**Issue by AnujMongia1** [AnujMongia1/COMP72070-Project-4-Section-3-Group-4#2]
the test is failing despite being correctly defined, currently working on this...

![image](https://github.com/AnujMongia1/COMP72070-Project-4-Section-3-Group-4/assets/124279770/7ce1f65c-7de2-489d-afa2-e9a500fd79e0)

**Comment by SUPERBOLIDEIRL** [comment]
The issue has now been fixed.
![chuj](https://github.com/AnujMongia1/COMP72070-Project-4-Section-3-Group-4/assets/122998649/3a156798-b8e9-4dff-85ef-2aff51b4bd7e)
